name: My_CI

on: [ pull_request ]

jobs:
  main-job-python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: SETUP - Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: SETUP - Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint mypy

      - name: CHECKS - Linting
        run: pylint **/*.py
        env: 
          PYTHONPATH: mfranceschi_minesweeper/

      - name: CHECKS - Static types
        if: always()
        run: mypy ./mfranceschi_minesweeper/minesweeper.py

      - name: CHECKS - Tests
        if: always()
        run: python -m pytest ./tests/

  check-without-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: CHECKS - Ensure no print
        if: always()
        run: "! grep -Rl 'print(' --include=*.py"
