name: My_CI

on: [ pull_request ]

env:
  SOURCE_DIR: ./mfranceschi_minesweeper
  MAIN_FILE: ./mfranceschi_minesweeper/main.py
  TESTS_DIR: ./tests/

jobs:
  main-job-python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        PYTHON_VERSION: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: SETUP - Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: SETUP - Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint mypy

      - name: CHECKS - Linting
        run: pylint **/*.py
        env: 
          PYTHONPATH: ${{ env.SOURCE_DIR }}

      - name: CHECKS - Static types
        if: always()
        run: mypy ${{ env.MAIN_FILE }}

      - name: CHECKS - Tests
        if: always()
        run: python -m pytest ${{ env.TESTS_DIR }}

  ensure-builds:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.7

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: SETUP - Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
  
      - name: SETUP - Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade build twine

      - name: CHECK - Build succeeds
        run: python -m build

      - name: CHECK - Twine is happy
        run: twine check dist/*

  check-without-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: CHECKS - Ensure no print
        if: always()
        run: "! grep -Rl 'print(' --include=*.py"
