name: My_CI

on: [ push, pull_request ]

env:
  PYTHON_VERSION: 3.9

jobs:
  main-job:
    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 60
      COVERAGE_TOTAL: 60

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint **/*.py

      - name: Run tests
        if: always()
        run: pytest .
