name: My_CI

on: [ push, pull_request ]

env:
  PYTHON_VERSION: '3.7'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
        run: 'python -m pip install --upgrade pip'

      - name: Pytest and coverage
        uses: alexanderdamiani/pytester-cov@v1.2.0
        with:
          # root directory to recursively search for .py files (default is .)
          pytest-root-dir: '.'

          # directory with pytest tests. if left empty will identify test(s) dir by default
          pytest-tests-dir: 'tests'

          # list of directories and/or files to ignore (default is )
          cov-omit-list: 'tests/*'

          # requirements filepath for project (default is requirements.txt)
          requirements-file: requirements.txt

          # fail if any single file coverage is less than threshold (default is 0)
          # cov-threshold-single:

          # fail if the total coverage is less than threshold (default is 0)
          cov-threshold-total: 50

  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Prepare pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

      - name: Run pylint
        run: pip install -r requirements.txt ; pylint **/*.py
